# Site settings
title: SSD Consultants
email: shamim@ssdconsultants.in
url:
description: "SSD Consultants is your trusted partner for end-to-end recruitment solutions. We specialize in helping organizations find, assess, and hire the right talent—managing the entire hiring process with efficiency, care, and expertise. From startups to established companies, we deliver recruitment strategies tailored to your goals."
keywords: "recruitment agency, talent acquisition services, job placement services, recruitment solutions, staffing agency for startups, recruitment consultants, hire top talent, professional recruitment services, employee recruitment agency, hiring solutions for businesses, best recruitment agency, startup recruitment services, temporary staffing solutions, executive search firm, IT recruitment agency, healthcare recruitment firm, recruitment process outsourcing (RPO), talent sourcing for companies, recruitment experts, job recruitment startup."
skills: "End to End Recruitment"
meta_author: Shamim Saiyed

# Google webmaster tools
google_verify: dvtpe9iPLmOYm2vfhqoIFf2jklyoczBzoAWqetPwu1Q

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 0b334f #FD6E8A
  secondary-dark: 508bae #A2122F

# Footer settings
footer:
  copyright: Shamim Marks
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
